name: example-environment
channels:
  - conda-forge
dependencies:
  - python3
  - numpy
  - pip
  - pip:
    - opencv-python
    - torch
    - torchvision
    - albumentations
    - numpy
    - matplotlib
    - segmentation_models_pytorch
    - scikit-learn